# Generated by Django 4.0.4 on 2022-04-13 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('mood', models.CharField(max_length=25)),
                ('genre', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
                ('photo', models.ImageField(blank=True, default='images/default.jpg', upload_to='image/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dramas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateField(auto_now_add=True)),
                ('body', models.TextField()),
                ('mood', models.BooleanField()),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dramas.drama')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
