# Generated by Django 4.0.4 on 2022-04-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dramas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='posted',
        ),
    ]
